[package]
name = "tn-engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
fastcrypto = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
thiserror = { workspace = true }
tn-types = { workspace = true }
tokio = { workspace = true, features = ["sync", "time"] }
tokio-stream = { workspace = true, features = ["sync"] }
tracing = { workspace = true }

# reth deps
reth-blockchain-tree = { workspace = true }
reth-chainspec = { workspace = true }
reth-errors = { workspace = true }
reth-evm = { workspace = true }
reth-execution-types = { workspace = true }
reth-node-api = { workspace = true }
reth-payload-builder = { workspace = true }
reth-primitives = { workspace = true }
reth-provider = { workspace = true }
reth-revm = { workspace = true }
reth-trie = { workspace = true }

[dev-dependencies]
# unit tests
eyre = { workspace = true }
narwhal-test-utils = { workspace = true }
reth-tracing = { workspace = true }
reth-tasks = { workspace = true }
tn-block-builder = { workspace = true, features = ["test-utils"] }
tn-types = { workspace = true, features = ["test-utils"] }
